### ISSUE TITLE
Add Support from API to detect Multiple Faces

### ISSUE THREAD

**Issue by muhammadsuheer** [muhammadsuheer/Reizel-face-detector#1]

**Comment by siddharth595** [comment]
Hey, can you please elaborate a little more on the issue or feature? Thankyou.

**Comment by muhammadsuheer** [comment]
> Hey, can you please elaborate a little more on the issue or feature? Thankyou.

Now this app can only detect one face in images like this whenerver you paste a link it only detects one face

![Screenshot 2022-10-13 154255](https://user-images.githubusercontent.com/58456635/195576689-cf3c3740-59e2-418f-a6d9-be7f33a45

But whenever i paste the link of image with more then one face it detects only 1 face like this 

![1 face](https://user-images.githubusercontent.com/58456635/195576819-a7fff370-0502-45ff-9610-3c9a82439cc9.jpg)
26c.jpg)


I need help to add functionality in app to detect multiple faces.

**Comment by siddharth595** [comment]
Thank you for the explanation. I have got a better understanding now. Please assign this to me.
